name: ROS2 CI

on:
  pull_request:
  push:
    branches:
      - boost
      - tcp
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          - rolling

    container:
      image: ros:${{ matrix.ros_distribution }}

    steps:
      - name: build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
