nodes:
  - name: /autoware/perception
    type: and
    list:
      - type: diag
        name: "topic_state_monitor_object_recognition_objects: perception_topic_status"
        hardware: topic_state_monitor
