/**:
  ros__parameters:
    blind_spot:
      use_pass_judge_line: true
      stop_line_margin: 1.0 # [m]
      backward_length: 50.0 # [m]
      ignore_width_from_center_line: 0.7 # [m]
      max_future_movement_time: 10.0 # [second]
      threshold_yaw_diff: 0.523 # [rad]
      adjacent_extend_width: 1.5 # [m]
      enable_rtc: true # if true, the scene modules should be approved by (request to cooperate)rtc function. if false, the module can be run without approval from rtc.
